-- Fleet Forecasting: new tables for maintenance tracking, peak overrides, and empty-leg offers

-- Aircraft Maintenance blocks (for capacity calculation)
create table aircraft_maintenance (
  id uuid primary key default uuid_generate_v4(),
  aircraft_id uuid references aircraft(id) on delete cascade not null,
  start_time timestamptz not null,
  end_time timestamptz not null,
  maintenance_type text not null default 'scheduled', -- 'scheduled', 'unscheduled', 'inspection', 'overhaul'
  notes text,
  created_at timestamptz default now()
);

-- Fleet forecast peak-day multiplier overrides (manual inputs for special events/holidays)
create table fleet_forecast_overrides (
  id uuid primary key default uuid_generate_v4(),
  date date not null,
  aircraft_category text not null, -- 'light', 'midsize', 'super-mid', 'heavy', 'ultra-long', 'turboprop', or 'all'
  peak_multiplier numeric(4,2) not null default 1.0,
  reason text,
  created_at timestamptz default now(),
  unique(date, aircraft_category)
);

-- Empty-leg offers generated by the action engine
create table empty_leg_offers (
  id uuid primary key default uuid_generate_v4(),
  aircraft_id uuid references aircraft(id) on delete cascade not null,
  offer_date date not null,
  from_icao text not null,
  to_icao text not null,
  discount_pct numeric(5,2) not null default 20.0,
  reason text not null default 'idle risk high',
  status text not null default 'active', -- 'active', 'converted', 'expired'
  created_at timestamptz default now()
);

-- RLS
alter table aircraft_maintenance enable row level security;
alter table fleet_forecast_overrides enable row level security;
alter table empty_leg_offers enable row level security;

create policy "staff_all" on aircraft_maintenance for all using (auth.role() = 'authenticated');
create policy "staff_all" on fleet_forecast_overrides for all using (auth.role() = 'authenticated');
create policy "staff_all" on empty_leg_offers for all using (auth.role() = 'authenticated');
